tb = int(input('digite o número para sua tabuada: '))
print('-' * 12)
print(f'{tb} x {1:2} = {tb*1}')
print(f'{tb} x {2:2} = {tb*2}')
print(f'{tb} x {3:2} = {tb*3}')
print(f'{tb} x {4:2} = {tb*4}')
print(f'{tb} x {5:2} = {tb*5}')
print(f'{tb} x {6:2} = {tb*6}')
print(f'{tb} x {7:2} = {tb*7}')
print(f'{tb} x {8:2} = {tb*8}')
print(f'{tb} x {9:2} = {tb*9}')
print(f'{tb} x {10:2} = {tb*10}')
print('-' * 12)
